### ISSUE TITLE
BuildDotenvConfig.rb failed on build

### ISSUE THREAD

**Issue by jsimonassi** [lugg/react-native-config#519]
I'm used version: 1.3.3 and compiled sucefuly, but after update to: 1.4.0 I got this error on this file BuildDotenvConfig.rb line 4, xcode said we had syntax error on it.

I fix just did not update yet to 1.4.0 and using 1.3.3.

**Comment by dubinam** [comment]
@jsimonassi Try to revert this changes 
https://github.com/luggit/react-native-config/commit/0c42216725fd686b93900038e089fd71f9f75424
or hardcoded the prev hash in package.json
I hope it will be fixed soon.

**Comment by luancurti** [comment]
@jsimonassi Have you checked if your `.env` file have spaces like ` MY_ENV='foo'`? Can you share the content of your `.env` file here to help us investigate this problem?

**Comment by dubinam** [comment]
Doesn't matter content inside .env. there is an error I side ruby file with
new if condition someone forget to add 'end'

**Comment by luancurti** [comment]
Thanks for the explanation @dubinam I think I [fixed](https://github.com/luggit/react-native-config/commit/61a970f6dc7aa41c4b3fdae736a1dc4b377704e7) this problem in `1.4.1` version @jsimonassi Can you test with the `1.4.1` to confirm that problem is fixed?

**Comment by mlazari** [comment]
Not sure if it's the same issue, but for me iOS build fails after updating from `1.3.3` to `1.4.1` because of empty lines and comments in env files: https://github.com/luggit/react-native-config/pull/516#issuecomment-724621992

**Comment by janpe** [comment]
My build is also failing, not because of empty lines but because of lines that are commented out.
