### ISSUE TITLE
Environment Variables Not Applied in Release Build Using react-native-config

### ISSUE THREAD

**Issue by Seokkitdo** [lugg/react-native-config#813]
I'm encountering an issue where environment variables defined in my .env files are not being correctly applied when building the release version of my app using react-native-config. Here is a summary of the problem:

1. I have multiple .env files (.env.production, .env.staging, .env.development) stored in a folder named env at the root of my project.

3. I verified that the environment variables are correctly loaded during development builds and staging builds.
4. However, when building for release (e.g., using assembleRelease or assembleStagingRelease), the environment variables are not included in the BuildConfig.java file, and default values are used instead.
```
Reading env from: .env
**************************
*** Missing .env file ****
**************************
```

Any insight into why the environment variables are not being correctly applied during the release build would be greatly appreciated. If there is a known workaround or additional configuration required, I would be glad to implement it.

Thank you for your assistance!

**Comment by sureshbakshi** [comment]
@Seokkitdo  I'm experiencing a similar issue. Were you able to find a solution?
